apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: untold-rewrite
spec:
  replacePathRegex:
    regex: ^/(config.json|index.html|robots.txt|sitemap.xml)$
    replacement: /verticals-data/untold/$1


---

apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: untold-root-rewrite
spec:
  replacePathRegex:
    regex: ^/$
    replacement: /verticals-data/untold/index.html

---

apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: untold-route
spec:
  entryPoints:
    - websecure
  routes:
    # Handle `/`
    - match: Host(`notes.feedless.org`) && PathPrefix(`/`)
      kind: Rule
      services:
        - name: feedless-web
          port: 80
      middlewares:
        - name: untold-root-rewrite

    # Handle vertical configs
    - match: Host(`notes.feedless.org`) && (Path(`/config.json`) || Path(`/index.html`) || Path(`/robots.txt`) || Path(`/sitemap.xml`))
      kind: Rule
      services:
        - name: feedless-web
          port: 80
      middlewares:
        - name: untold-rewrite

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: untold-ingress
  annotations:
    app.kubernetes.io/name: untold-ingress
    cert-manager.io/cluster-issuer: letsencrypt
    traefik.ingress.kubernetes.io/force-ssl-redirect: "true"
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - api.notes.feedless.org
        - notes.feedless.org
      secretName: feedless-org-tls
  rules:
    - host: api.notes.feedless.org
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: feedless-core
                port:
                  number: 8080
    - host: notes.feedless.org
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: feedless-web
                port:
                  number: 80
