apiVersion: v1
kind: Secret
metadata:
  name: upcoming-secrets
type: Opaque
stringData:
  # github
  oauthProvider: "github"
  oauthProviderClientId: ""
  oauthProviderClientSecret: ""
  oauthProviderRedirectUri: "https://api.lokale.events/login/oauth2/code/github"

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: upcoming-config-json
data:
  config.json: |
    {
      "apiUrl": "https://api.lokale.events",
      "product": "upcoming",
      "eventRepositoryId": "TBD",
      "operatorName": "TBD",
      "operatorAddress": "TBD",
      "operatorEmail": "TBD",
      "offlineSupport": false
    }

---

apiVersion: v1
kind: Secret
metadata:
  name: upcoming-tls
type: kubernetes.io/tls
data:
  tls.crt: 'fullchain.pem'
  tls.key: 'privkey.pem'
