# kubectl apply -f https://github.com/cert-manager/cert-manager/releases/latest/download/cert-manager.yaml
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    #    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: feedlessapp@proton.me
    privateKeySecretRef:
      name: letsencrypt
    solvers:
      - http01:
          ingress:
            class: traefik

---

apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: feedless-org-tls
spec:
  secretName: feedless-org-tls
  dnsNames:
    - grafana.feedless.org
    - feedless.org
    - api.feedless.org
    - plausible.feedless.org
    - api.rssproxy.feedless.org
    - rssproxy.feedless.org
    - api.visualdiff.feedless.org
    - visualdiff.feedless.org
    - api.notes.feedless.org
    - notes.feedless.org
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer


---

apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: upcoming-tls
spec:
  secretName: upcoming-tls
  duration: 2160h  # 90d
  renewBefore: 360h  # 15d
  dnsNames:
    - api.lokale.events
    - www.lokale.events
    - lokale.events
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer

---

apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: rssproxy-migor-org-tls
spec:
  secretName: rssproxy-migor-org-tls
  duration: 2160h  # 90d
  renewBefore: 360h  # 15d
  privateKey:
    rotationPolicy: Never
  issuerRef:
    name: letsencrypt
    kind: Issuer
  dnsNames:
    - api.rssproxy.migor.org
    - rssproxy.migor.org
    - api.rssproxy-v1.migor.org
    - rssproxy-v1.migor.org
