spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        #        use_sql_comments: true
        format_sql: true

logging:
  pattern.file: %d{dd-MM-yyyy HH:mm:ss.SSS} [%thread] %-5level %logger{36}.%M - %msg%n
  #  file:
  #    name=: ./database.log
  level:
    root: INFO
    #    WebToFeedTransformer: DEBUG
    ch.qos.logback: off
    org.springframework.security.web.csrf: debug
    org.hibernate.type: trace
