spring:
  devtools:
    add-properties: false
  main:
    banner-mode: off
  mail:
    test-connection: true
    properties:
      mail:
        smtp:
          auth: true
          connectiontimeout: 10000
          timeout: 10000
          writetimeout: 10000
          starttls:
            enable: true

logging:
  level:
    root: ${APP_LOG_LEVEL}
    ch:
      qos:
        logback: off

graphql:
  playground:
    enabled: false

app:
  apiGatewayUrl: ${APP_API_GATEWAY_URL}
  appHost: ${APP_HOST_URL}
  defaultDateFormat: ${APP_DEFAULT_DATE_FORMAT}  # dd-MM-yyyy
  defaultTimeFormat: ${APP_DEFAULT_TIME_FORMAT}  # HH:mm
  jwtSecret: ${APP_JWT_SECRET}
  rootEmail: ${APP_ROOT_EMAIL}
  rootSecretKey: ${APP_ROOT_SECRET_KEY}
  actuatorPassword: ${APP_ACTUATOR_PASSWORD}
  whitelistedHosts: ${APP_WHITELISTED_HOSTS}
  mail:
    sender: ${APP_MAIL_SENDER}
